### ISSUE TITLE
Some UI elements don't exit on LEFT where it's expected

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#108]
We have an informal UX guideline - UI elements need to exit on LEFT wherever possible. Some UI elements don't, however:

- [ ] `NumpadCharElement` has to exit on LEFT if the value is empty (at least until we have a cursor implemented)
- [x] `TextReader` should exit on LEFT when horizontal scroll is in the leftmost position

**Comment by derivmug** [comment]
I have made some a small change to TextReader which makes it exit on LEFT when it's in the leftmost position. The changes are in the `derivmug-matrix` branch

**Comment by derivmug** [comment]
NumpadCharInput calls the following method on LEFT, so I believe this might be already implemented.

`    def deactivate_if_first(self):
        """ Deactivates the UI element if it hasn't yet had a character entered """
        if self.position == 0:
            self.deactivate()`

**Comment by CRImier** [comment]
ohh. why wouldn't it work then? let me see

**Comment by CRImier** [comment]
Okay. Tested, and understood why it didn't work for me - this is fixed, thank you @derivmug =)
