### ISSUE TITLE
Add Canvas.rotate and Canvas.paste

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#158]
I'm working more and more on various functions that allow to use `Canvas` in yet unforeseen ways. For example, in `GridMenu`, apart from the `Canvas` used to draw the menu itself, an additional `Canvas` together with `MockOutput` is used to crop the text in the grid cell so that it doesn't overflow. So, there are two functions I think we should have

- [x] Add `Canvas.paste(image, coords)`, which would paste the supplied `PIL.Image` onto the canvas, with top left corner of the image positioned at `coords`. There's already the `Canvas.image.paste(image, coords)` method that does exactly that, we just need to wrap it into our own API, add a `check_coordinates` call, documentation and tests.
- [x] Add `Canvas.rotate(degrees)`, which would take a canvas with a WxH image, rotate the image to a certain amount of degrees and update the canvas to have proper `width` and `height` attributes.
  - [x] For a start, it would be OK to only support 0/90/180/270 rotation, but having an option to supply arbitrary degrees would be great.

**Comment by LouisPi** [comment]
I should be able to do this. Basically wrappers for PIL Image paste and rotate.

**Comment by CRImier** [comment]
Yep, same as the other wrappers we already have in `Canvas`.

**Comment by CRImier** [comment]
@LouisPi thank you for your help!
