### ISSUE TITLE
Adding "save previous faulty config under different filename" feature to the read_or_create_config helper

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#38]
The [read_or_create_config helper](https://github.com/ZeroPhone/ZPUI/blob/master/helpers/config_parse.py#L16), upon encountering a config file that won't parse, replaces it with the default config given by the app. However, in case of users editing their configs and making mistakes, it can lead to users losing their configs with many modifications just because of a single JSON syntax error. So, in order to be user-friendly, the helper would need to copy the previous config into another file (same directory, different filename), allowing the user to restore their changes. The feature should also be on by default (accessible through a keyword argument, optionally).

**Comment by monsieurh** [comment]
On it ! 
For some reason I can't assign myself to the issue though.

**Comment by CRImier** [comment]
Somehow, managed to assigned you =)

**Comment by CRImier** [comment]
Closed by #47
