### ISSUE TITLE
[Discussion] Allowing to tweak logging levels from a config file and command-line

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#40]
Changing default logging levels for module-specific loggers currently requires editing the code of the module. Ideally, that could be done using a `config.json` setting, possibly, also command-line switches, to allow tweak each individual logger both separately and permanently.

**Comment by monsieurh** [comment]
So that's the specs as i understand them :
- be able to change the log level of a single application
- be able to override all log level for all apps
Additional questions :
Should all loggers log to `zpui.log` logfile ?

**Comment by CRImier** [comment]
The scenarios are:
- Temporarily enabling verbose logging for a part of ZPUI. Say, you encounter a bug that seems to be in the input subsystem. You could then launch ZPUI as `python main.py -L "input/input.py:debug"` (just for an example) and see all the input subsystem logs with `debug` level or higher.
- Enabling verbose logging for an app, so that you could collect logs/exceptions from an app while it's being used - so that it's easier for developers to debug their apps while using them as part of system-wide ZPUI install, and so that users can enable verbose logging for this one app, collect logs, filter them and then send them to the developer (in case the app is doing something wrong).
- Enabling verbose logging for certain subsystems of ZPUI after making fundamental changes, to understand whether there's anything wrong happening after those changes have been introduced (to be mostly used during testing).

The main problem is enabling verbose logging for an application without having to edit its code - it's time-consuming, and updating code from a repo might result in conflicts. Also, there shouldn't be "unstaged changes" messages in `git status` all the time!

So, addressing your specs:
- the per-application log level change is necessary
- global log-level change is not necessary (I don't yet have a scenario where you have to make __everything__ verbose, any ideas?)
- logging level selection priorities would look something like this: (starting with "more important")
 1. commandline switches
 2. logging config file
 3. arguments passed to "setup_logger"
- I don't see why having additional logfiles would be necessary - _yet_. Any ideas?

**Comment by monsieurh** [comment]
Post-IRC discussion clarification :
- FIX NEEDED : All apps use the same logger because `__name__` resolves to `main.py`

**Comment by CRImier** [comment]
@monsieurh That seems to have been a cosmetic issue, rather than "resolves" issue - fixed it by changing the logging format, 3f4c1678c

**Comment by CRImier** [comment]
Should be solved once #89 is merged!

**Comment by CRImier** [comment]
Aaand we have a config file-based solution, which means that this is solved!

**Comment by CRImier** [comment]
Thanks to @monsieurh for solving this =)
