### ISSUE TITLE
Canvas subsystem

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#52]
After #3 was started and the initial refactoring of UI was merged, the UI is slowly moving towards using canvases for rendering in places where it's useful. However, there are some problems:

- Canvas is not as straightforward to initialize as it could be:
```
from luma.core.render import canvas
...
c = canvas(self.o.device)
c.__enter__()
draw = c.draw
... #Draw things on canvas
image = c.image
```
It could definitely be shortened, and the `luma.` import could be avoided in favour of using a ZPUI-internal import.
- There are canvas-related objects and functions that could be moved into the canvas subsystem - [such as this one](https://github.com/ZeroPhone/ZPUI/blob/168aba928153721d261b2c3cc0ab58080337248f/ui/loading_indicators.py#L28)
- There's no documentation on using canvases for ZPUI needs.
- The luma.canvas implementation uses `del` for cleanup, need to research - is it really necessary?

Additionally, we could simplify and optimize PIL drawing functions:

- When drawing text, the default font seems to be loaded on each text() call. We can override the text() call (that's currently being passed through using __getattr__) to substitute the default font, already loaded, each time a `font` kwarg is not present. In the future, once we have some kind of font subsystem, we could integrate it, too.
- Currently, when drawing text, a "fill" attribute usually has to be set each time. We can set it to "white" by default (makes the most sense for OLED screens) and only override it when other value is supplied.
- We can also implement negative text (or other primitive) offsets - for example, a `c.text((-0, y), text)` call would draw text so that its bottom margin is 10px from the bottom of the screen.
- To make code even shorter, we can add a `.display()` method, which would call `o.display_image()` directly, for even quicker drawing on the screen!

Proposed TODO:

- [x] Make a canvas subsystem inside ZPUI (for example, `ui.canvas`), allowing to easily&quickly get a canvas, draw something on it and show it on the screen
- [x] Document all functions
- [x] Aggregate all the canvas-related functions into the canvas
  - [x] `invert_rect_colors`
  - [x] `draw_centered_text` (from `CenteredTextRenderer`)
  - [x] `get_centered_text_bounds` (from `CenteredTextRenderer`)
- [x] Only load the default font once, then substitute it unless other font is desired (done in `main_screen` branch)
- [x] Set default "fill" attribute to white - at least, for text (see what makes sense for other primitives, maybe "outline" is a sensible default for others)
  - [x] `text`
  - [x] `rectangle`
- [x] Implement negative offsets
  - **UPD** - it has come to my attention that negative offsets already make sense. If so, a "-1" string could be passed instead of a '-1' number.
- [x] Add a `display()` method
- [x] Research compatibility with luma.core.virtual helpers and luma viewports
- [x] Make usage examples - with pictures
- [x] Verify if `del` has to be used (question asked [here](https://github.com/rm-hull/luma.core/issues/123)) (followed up [here](https://github.com/python-pillow/Pillow/issues/3002))
- [x] Add tests

Links:
* [PIL canvas documentation](http://pillow.readthedocs.io/en/3.1.x/reference/ImageDraw.html)
* [luma.canvas implementation that we (used to) work around](https://github.com/rm-hull/luma.core/blob/master/luma/core/render.py)

**Comment by CRImier** [comment]
This became necessary for #8, so the canvas subsystem has now been created in multiple_contexts branch, and existing code ported over ( no documentation or examples yet, and functions haven't yet been ported over either ).

**Comment by BeauSlim** [comment]
Isn't luma's Canvas mostly a wrapper around PIL.ImageDraw to let you use python's "with"?  I don't think you are intended to access __enter__ directly, and you probably want plain old PIL.ImageDraw instead?  

I could be totally wrong.  Maybe you have to use luma.core.render.canvas in order to draw on luma.core.virtual objects.  All of these image objects, and imagedraw objects and real devices, and luma.core.virtual devices like hotspots, and viewports can be very confusing.  Together, they could make a pretty cool GUI, though.

**Comment by CRImier** [comment]
@BeauSlim It is kind of a wrapper, but dropping luma_canvas for plain ImageDraw isn't enough, we still need some kind of wrapper around ImageDraw, since there's a little bit of boilerplate involved and it would be great to have a wrapper around that. [Here's the initial version I've written](https://github.com/ZeroPhone/ZPUI/blob/multiple_contexts/ui/canvas.py), undocumented - and [here's an example of its usage](https://github.com/ZeroPhone/ZPUI/blob/multiple_contexts/ui/loading_indicators.py#L151).

**Comment by CRImier** [comment]
Agreed on the "would make for cool GUI", it definitely could. I don't think we need to use the luma canvas for core.virtual or viewports - I'm sure that, even if there's a hard dependency (which is unlikely), we can work around that - otherwise, there should be a simple way to use, say, viewports with our implementation. Either way, it's our implementation, we control it and we no longer depend on it, which is IMO great - no `__enter__` needed anymore, and we can call ImageDraw functions directly through the canvas object =)

**Comment by BeauSlim** [comment]
You just solved something for me.  PIL's separation of line and text drawing into PIL.ImageDraw, and the paste function into PIL.Image is a pain in the butt to work around while abstracting.  You've essentially combined them.  Kind of.  Why didn't I think of that, haha.   I'm going to use your Canvas, add a paste function, and see how that works out.

**Comment by CRImier** [comment]
Our canvas implementation is now in the `devel` branch, in `ui.canvas.py` file (not yet documented)

**Comment by CRImier** [comment]
@monsieurh Would you be interested in working on `Aggregate all the canvas-related functions into the canvas` task? As the canvas subsystem is already in `devel`, it makes sense =)

**Comment by CRImier** [comment]
Implemented most of the functions - now I just need to add usage examples, move all the canvas functions into it, add default font loading and do some `luma` research.

**Comment by CRImier** [comment]
Documentation now [available here](http://zpui.readthedocs.io/en/devel/ui/canvas.html), with a couple of usage examples [available here](http://zpui.readthedocs.io/en/devel/howto.html#draw-on-the-screen)

**Comment by CRImier** [comment]
@BeauSlim Are there any more functions we could add? You mentioned some kind of "paste" function, do you mean something like `ImageDraw.bitmap`?

**Comment by CRImier** [comment]
Added docs with images [in the devel branch docs](http://zpui.readthedocs.io/en/devel/howto.html). Until there are further wishes, this is finished!
