### ISSUE TITLE
Emulator and NumpadCharInput

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#77]
- `NumpadCharInput` doesn't fully work on emulator, since F1 and F2 keys are not actually available. The fix has to be applied in multiple places:
  - [x] Make UniversalInput check for availability of all action keycodes of NumpadCharInput (including F1 and F2)
  - [x] Make the pygame_input driver forward F1 and F2 keys (and any other keys which would be used by ZPUI UI elements such as PAGEUP and PAGEDOWN)
- [x] Emulator doesn't forward numpad keys (`KEY_KP{number}`), making it harder to use `NumpadCharInput`, `NumberedMenu` and the like - you have to use the number key row instead of the numeric keypad that most PC keyboards (and some laptops) have.

**Comment by CRImier** [comment]
pygame_input now forwards F1 and F2 (as well as other relevant keys), and forwards keypad keys too - thanks to @bolens1112 !

**Comment by bolens1112** [comment]
Pardon my ignorance but I don't understand the part talking about checking for the availability of action keycodes. Is this to make sure that something else has not captured the keys? Or something else?

**Comment by CRImier** [comment]
`NumpadCharInput` uses a set of keys. If *all* of them aren't accessible, it's unclear whether it can work. We have two ways here:
1. Check if *all* keys in the keymap are accessible, if not, `UniversalInput` will use `ArrowKeysCharInput`
2. Check if *all* crucial functions of the `NumpadCharInput` are accessible - that is, "backspace", "accept" and "cancel". If all these functions aren't accessible in some way, `UniversalInput` will use `ArrowKeysCharInput`

First way is quicker to implement and will cover the majority of usecases; second way is IMO the proper way to do it, but the amount of additional usecases it covers isn't that significant.

**Comment by CRImier** [comment]
Done!
