### ISSUE TITLE
Legacy: single-context UI flow

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#8]
From the beginning, pyLCI was single-context - no multitasking, the workflow is menu-driven, you need to go back in a menu if you want to exit the current application and go to another. No notification support - the problem is that UI elements wouldn't know if they lost context, so if screen contents were suddenly changed, a menu wouldn't know that they did, and if input callbacks were set by something that popped on the screen, the UI element would never know it happened. The whole flow is quite linear, and a single UI element accidentally setting callbacks at the wrong time can make the interface not respond. This also means that there can be no notifications, no hotkeys to switch to another app instantly, no "press call button to get to call menu", and this obviosly isn't a good architecture for phone UI, where any app could be requested at any moment. 

One of the main problems is that InputListener and Screen objects (``i`` and ``o``) speak to hardware directly, there's no object that could be passed to UI elements so that they wouldn't have to distinguish between "app active" and "app not active" states while operating. So, proxy objects have to be developed.

Status:
- [x] InputProxy objects
- [x] OutputDevice specifications
- [x] OutputProxy objects
- [x] Automatic proxy object creation for each app
- [x] Automatic proxy object assignment to apps
- [x] Support for ZPUI-global callbacks (related to #42 )
- [x] Creating threads for each starting application
- [x] Exposing context switching to users&apps
- [x] Sample app that uses context switching for useful functionality
- [x] Tests
- [x] Documentation
- [x] Examples in "How to"

Optional:
- Passthrough the backlight control capability -

**Comment by CRImier** [comment]
Started work in [contexts](../tree/contexts) branch, writing context object and replacing the system-wide i and o objects by those.

**Comment by CRImier** [comment]
Work continues in [multiple_contexts](https://github.com/ZeroPhone/ZPUI/tree/multiple_contexts) branch

**Comment by CRImier** [comment]
Status:
- [x] InputProxy objects
- [ ] OutputProxy objects
- [x] Automatic proxy object creation for each app
- [x] Automatic proxy object assignment to apps
- [ ] Support for ZPUI-global callbacks (related to #42 )
- [ ] Tests

**Comment by CRImier** [comment]
Discussion on IRC before the "Creating threads for each starting app" completion
```
<CRImier> Trying to wrap my head around the context work
<CRImier> Like, I have this app with one menu, and it's supposed to make a "hotkey menu"
<monsieur_h> what's the "hotkey menu" exactly ?
<CRImier> Like, whichever app you're in, you press a key and the menu pops up, and it has all sorts of useful things like "turn on USB", "flashlight", "take a screenshot"
<CRImier> I used the screenshot functionality for the 2048 game writeup screenshots
<CRImier> https://hackaday.io/project/19035-zerophone-a-raspberry-pi-smartphone/log/71390-writing-a-2048-game-for-a-zerophone
<CRImier> But, as of now, that app is a hack, and it only can properly work with contexts, where input and output objects are actually separate
<monsieur_h> gotcha
<CRImier> So now, I understand that I need to make threads for each app that has a separate context
<CRImier> And run that thread when a context is switched
<monsieur_h> that or, maybe the android design might be another solution
<CRImier> The Android design?
<CRImier> You mean, apps being separate processes and all that?
<CRImier> That's coming, but not too soon
<monsieur_h> I mean the intent-based behaviour
<monsieur_h> can be painfull at times, but it's really tweakable to hell
<CRImier> That's a great tip
<CRImier> This is something I've not heard of yet
<CRImier> So, I'll read on it, and then take a break in coding for a couple of hours and just think about it =)
<CRImier> "Intents are asynchronous messages which allow application components to request functionality from other Android components."
<CRImier> http://www.vogella.com/tutorials/AndroidIntent/article.html
<CRImier> That's going to be an interesting addon to the contextswitching thing
<CRImier> Like, calling a WiFi menu
<monsieur_h> so basically every screen (even subscreen within the same app) work on a intent-based architecture
<CRImier> "A component can register itself via an intent filter for a specific action and specific data. An intent filter specifies the types of intents to which an activity, service, or broadcast receiver can respond to by declaring the capabilities of a component."
<monsieur_h> so everytime you press something, you actually make a call which is like MainThread.HEY_I_WANT_TO_DO_THAT(Intent.OpenCameraApp)
<CRImier> That's similar to "actions" that I was speaking of in https://github.com/ZeroPhone/ZPUI/issues/42
<monsieur_h> Mainthread answer with all the apps handling Intent.OpenCameraApp, and you get to pick one or set one by default.
<CRImier> Hmm, you mean it in the "each button press, even within same app, is an intent"?
<CRImier> wait, clarification
<monsieur_h> software buttons, yes
<CRImier> "each button press that leads somewhere else"
<monsieur_h> all "link"
<CRImier> Ahha
<monsieur_h> exactly
<CRImier> Wait, "link"?
<monsieur_h> errrr
<monsieur_h> everytime you have a small animation like "oooh that window poped up from below/left/right"
<CRImier> Ahha
<monsieur_h> but sometimes you can do  MainThread.HEY_I_WANT_TO_DO_THAT(Intent.OpenCameraApp, butOnlyWithinMyPackage=True)
<monsieur_h> to prevent other apps from taking over your flow
<CRImier> That's great!
<CRImier> I'm going to need time to wrap my head around it
<CRImier> However, I see one thing - it's very likely to be based on threads, too
<CRImier> Or not
<CRImier> Hmm
<monsieur_h> yes, no reason not to
<CRImier> Alright, I'll think about it, and implement thread support (at least parts of it) in the meanwhile
<monsieur_h> depends on what you need
<CRImier> Well, I wouldn't like to add threads where they're not necessary
<CRImier> That's why I'm going to need to think about it =)
<monsieur_h> some may be
<monsieur_h> so they can themselve run a MainThread.HEY_I_GOT_AN_INCOMING_CALL_PLS_HANDLE(Intent.Call)
<monsieur_h> or something like that
<CRImier> Dammit, that's a lot of enums =D
<CRImier> *potentially a lot of enums
<monsieur_h> or just ints
<monsieur_h> or even bitmasks
<monsieur_h> dunnow
<CRImier> Hmm, you're absolutely right, that could work wonders
```

**Comment by CRImier** [comment]
One of the problems is proxying input and output methods. While there should be no interaction with hardware while an app interacts with a non-active context proxy (tries to output data to screen or set callbacks), some things that an app might need can require changes of the state of output/input proxy - such as enabling cursor on a character display, or starting new InputProcessor threads. So, it seems that work that was started in #24 needs to be continued (bringing output devices to certain standards), and tests need to be written that'd check the context manager behaviour. In general, I think we should somehow save the state changes, and apply them when the context is next activated.

**Comment by monsieurh** [comment]
Thought about it some more: regarding the enum/int/bitmask thing. I thing we should go with strings instead.

Something normalized such as:
`zpui.system.call` indicates actions related to calling
`zpui.system.call.initiate`, `zpui.system.call.hangup` being possibles actions (just an example).

But basically, now that I think of it, we're just reinventing D-Bus. Maybe we should piggyback dbus instead ?

**Comment by CRImier** [comment]
DBus is a great thing and we're definitely going to use it at some point, but, for now, the communication will only be inside the single process, at least until #5 is implemented. Having said that, I've taken a look at the [FreeSmartphone API specification](freesmartphone.org) and I'm going to try and base the ZeroPhone API on it =)

**Comment by CRImier** [comment]
OutputProxy and InputProxy objects now work as intended, context switching works at a first glance, output device specifications have been designed and integrated (#24). Now I'm going to use the context-switching branch in day-to-day usage for a couple of days (until I get to finish the remaining tasks, when I'll feel safe about merging this), see how it goes.

**Comment by CRImier** [comment]
Everything from major tasks done - now it only needs examples, which I will do later.

**Comment by CRImier** [comment]
Examples added, everything is done. First major issue finished!
